# Use root/example as user/password credentials
version: '3.1'

services:
  #mysql Database service
  db-myplayer:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    restart: always
    environment:
      MYSQL_DATABASE: myplayer_orm
      MYSQL_USER: root
      MYSQL_PASSWORD: Liam1234
      MYSQL_ROOT_PASSWORD: Liam1234
      DB_HOST: db-myplayer
    ports:
      - "3307:3306"
    expose:
      - "3307"

    volumes: 
      - ./my-db:/var/lib/mysql

  mysql-workbench:
    image: ghcr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - 4000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

  api-myplayer:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
     - 8080:8080
    expose: 
      - "8080"
    environment:
      PORT: 8080
      DB_HOST: db-myplayer
      DB_USER: root
      DB_PASSWORD: Liam1234
      DB_NAME: myplayer_ORM
      DB_NAME_TEST: myplayer_test
      DB_NAME_PRODUCTION: myplayer_test
      ACCESS_TOKEN_SECRET: 1234
      REFRESH_TOKEN_SECRET: 12345
      ELASTIC_ID: My-Player:ZWFzdHVzMi5henVyZS5lbGFzdGljLWNsb3VkLmNvbTo5MjQzJDMzYTNmODBlYWVkMzQ4OTE4N2JmMjZhZTk1MDAzNGJiJDBiYzMzZGZjMWNhMDQzYTc4MWU2ZWNmNjA0N2ZhMTg1
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: LQgaUr5rKdV6gy5HkUylZJvG
    depends_on: 
      - db-myplayer

  app-myplayer:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes: 
      - '/usr/app/client/node_modules'
      - ./client:/usr/app/client
    ports:
      - 3030:3030
    expose: 
      - "3030"
    depends_on: 
      - api-myplayer
    
volumes:
  db-myplayer:
    driver: local